Classes/Editor/MovableViews/MovableViewCanvas.swift
Fixes an issue where trash can is covered with the stickers. You can see the problematic screen capture [here](https://drive.google.com/file/d/1rc6fKEbC6FlisqTa8WViDwQHsMsXEThg/view?usp=sharing).
Prerequisites:
Checkout this branch
cd to `KanvasCameraExample`
run `bundle install` then `bundle exec pod install`
- Run the example app
- Tap start
- Add an image
- Add some stickers at the bottom area
- Tap and hold a sticker to prompt the “Trash Can” icon to appear
- Observe that Trash Can is visible
=> Fix trash can getting covered with stickers

Classes/Editor/EditorViewController.swift, Classes/Settings/CameraSettings.swift
The `animateEditorControls` setting will enable/disable the movement animation on the editor controls.
When on these controls move up to to their positions like a "Magic Move" transition.
When off, the controls will not animate into position.
The "Before" example shows the enabled state for the setting.
The "After" example shows the disabled state for the setting.
https://user-images.githubusercontent.com/3250/107470042-031c9200-6b28-11eb-8476-c2550c6f2d3c.mp4
https://user-images.githubusercontent.com/3250/107470072-0f085400-6b28-11eb-8ed0-fdd8548dc188.mp4
=> Adds `animateEditorControls` setting to disable editor control animations

.circleci/cache-version, Classes/Camera/CameraController.swift, Classes/MediaPicker/MediaPicker.swift, Classes/MediaPicker/MediaPickerViewController.swift, KanvasExample/KanvasExample/ExampleKanvasDashboardController.swift, KanvasExample/KanvasExample/KanvasExampleViewController.swift, KanvasExample/KanvasExampleTests/Camera/CameraControllerTests.swift
The media picker will be implemented by the calling application so that it can choose to display its own interface (e.g. [WPMediaPicker](https://github.com/wordpress-mobile/MediaPicker-iOS) for WordPress iOS).
For now, the `KanvasMediaPickerViewController` remains as a default bridge to the system photo picker.
- `MediaPicker.swift` contains the new protocol type which just has a method to present the UI with corresponding settings and delegate object.
- The initializer in `CameraController` has been cleaned up a bit so that we don't have two of them. The properties with default internal types are now declared as initial values at the property site.
- Open the example app.
- Ensure that the Media Picker still functions as expected.
=> Adds a media picker type

Classes/Camera/FilteredInputViewController.swift, Classes/Editor/EditorView.swift, Classes/Editor/EditorViewController.swift, Classes/Rendering/MediaExporter.swift, Classes/Rendering/MediaPlayer.swift, Classes/Rendering/Metal/MetalPixelBufferView.swift, Classes/Rendering/OpenGL/GLPixelBufferView.swift, Classes/Rendering/PixelBufferView.swift, Classes/Rendering/VideoCompositor.swift, Classes/Settings/CameraSettings.swift, KanvasExample/KanvasExample.xcodeproj/project.pbxproj, KanvasExample/KanvasExample/FeatureTableView.swift, KanvasExample/KanvasExample/KanvasExampleViewController.swift, KanvasExample/KanvasExampleTests/Editor/EditorControllerTests.swift, KanvasExample/KanvasExampleTests/Editor/EditorViewTests.swift, KanvasExample/KanvasExampleTests/Rendering/MediaPlayerViewTests.swift, KanvasExample/KanvasExampleTests/Rendering/Metal/MetalPixelBufferViewTests.swift
A new `scaleMediaToFill` setting will enable the developer to toggle the `mediaContentMode` of the buffer views. Each buffer view should resize its contents to match this content mode setting.
This fills the screen with the media according to its aspect ratio and crops its sides as necessary.
1. Enable the `Metal Filters`, `Camera Metal`, and `Scale Media to Fill` flags, disable the `Camera OpenGL` and `Camera OpenGL Capture` flags.
2. Take photos and video and import media from the photo library.
3. Ensure that media is properly displayed and exported with contents.
| Enabled | Disabled (before) |
| ------- | ----------------- |
| <a href="https://user-images.githubusercontent.com/3250/108017096-4d42bf00-6fd1-11eb-845e-a460ee09d6a8.PNG"><img …
=> Add `scaleMediaToFill` setting enabling media scaling

Classes/Camera/CameraPermissionsViewController.swift, Classes/Constants/KanvasColors.swift, KanvasExample/KanvasExample.xcodeproj/project.pbxproj, KanvasExample/KanvasExample/KanvasCustomUI.swift
Adds permissions button colors properties to `KanvasColors`:
* `KanvasColors.permissionsButtonColor`
* `KanvasColors.permissionsButtonAcceptedBackgroundColor`
We want to customize these colors a bit for WordPress iOS: https://github.com/tumblr/kanvas-ios/issues/54
=> Add Permissions Button color customization

Classes/Camera/Filters/CameraFilterCollectionController.swift
This PR fixes an issue where the selected filter is reset after sending the app to background and bringing back.
**To Test**
Checkout this branch
cd to KanvasCameraExample
run bundle exec pod install
Run the example app
Tap start
Change the camera filter via the rounded icon above the big record button
Send the app to background
Bring the app from background
Verify the selected filter is kept
=> Fix filter getting reset after sending the app to background

Classes/Camera/CameraPermissionsViewController.swift, Classes/Constants/KanvasStrings.swift, Classes/Editor/EditorView.swift, Classes/Editor/MovableViews/MovableViewCanvas.swift, Classes/Editor/MultiEditor/MultiEditorViewController.swift, Classes/Editor/Text/EditorTextView.swift, Classes/Utility/IgnoreTouches/IgnoreTouchesView.swift, Classes/Utility/TrashView.swift, Kanvas.podspec, KanvasExample/Podfile.lock
* Adds customizable `KanvasStrings.shared` instance with permissions screen strings for customization. Similar to the way we are customizing `KanvasFonts` and `KanvasColors` for now.
* Adds the ability delete a frame from the Multi Editor screen. The `UIDropInteractionDelegate` APIs are used for this.
https://user-images.githubusercontent.com/3250/108441388-3f2fb100-7212-11eb-884a-3365b76fd97b.mp4
* Sets a white color for the Font Selector button when special fonts are used (this must be tested against WordPress iOS to verify the change).
| Before | After |
| ------ | ------|
| ![CleanShot 2021-02-18 at 17 59 14@2x](https://user-images.githubusercontent.com/3250/108441775-1825af00-7213-11eb-85c5-01c36a8769a7.png) | ![CleanShot 2021-02-18 at 17 54 …
=> A few minor Bug Fixes

Classes/Analytics/KanvasAnalyticsProvider.swift, Classes/Camera/CameraController.swift, Classes/MediaPicker/MediaPickerViewController.swift, KanvasExample/KanvasExample/KanvasAnalyticsStub.swift
This API change is necessary so that different types of media are selectable at once. The analytics providers will have to update their APIs to expect this and log it appropriately.
* Changes `logMediaPickerPickedMedia` to produce multiple media types for multi-selection:
```diff
--- func logMediaPickerPickedMedia(ofType mediaType: KanvasMediaType)
+++ func logMediaPickerPickedMedia(ofTypes mediaTypes: [KanvasMediaType])
```
* Moves `KanvasAnalyticsProvider` to Swift protocol to avoid issues with handling enums in arrays in Objective-C.
**NOTE: This should be safe since Tumblr's implementation is written in Swift (although it is an @objc class, it can still implement these methods in Swift).**
* Adds a `PickedMedia` type to encapsulate various types of media instead of having multiple …
=> Add multiple item selection to Media Picker

Classes/Camera/CameraController.swift, Classes/Rendering/MediaPlayer.swift, Classes/Utility/Device.swift, Kanvas.podspec
Related WordPress PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/15996
- Appends all added segments to the end of existing segments.
- Adds the iPhone 12 Pro to the `belongsToIPhoneXGroup`. This should be removed in the future to rely on the `safeAreaLayoutGuide` so it's not necessary to keep updating with changing screen sizes.
| Before | After |
| ------ | ----- |
| <a href="https://user-images.githubusercontent.com/3250/109604860-7723d780-7ae1-11eb-9614-279b07298144.png"><img src="https://user-images.githubusercontent.com/3250/109604860-7723d780-7ae1-11eb-9614-279b07298144.png" width="300"></a> | <a href="https://user-images.githubusercontent.com/3250/109604912-8a36a780-7ae1-11eb-98d2-6c92ca00bbf0.png"><img src="https://user-images.githubusercontent.com/3250/109604912-8a36a7 …
=> Stories bug fixes for 16.8 release

Classes/Camera/CameraController.swift, Classes/Editor/EditorViewController.swift, Classes/Editor/MultiEditor/MultiEditorViewController.swift, Classes/Editor/Text/EditorTextView.swift, Classes/Editor/Text/MainTextView.swift, Classes/MediaClips/MediaClipsCollectionCell.swift, Classes/MediaClips/MediaClipsCollectionController.swift, Classes/MediaClips/MediaClipsCollectionView.swift, Classes/Settings/CameraSettings.swift, Kanvas.podspec, KanvasExample/KanvasExampleTests/Editor/MultiEditor/MultiEditorControllerTests.swift, KanvasExample/KanvasExampleTests/Editor/Text/EditorTextControllerTests.swift, KanvasExample/KanvasExampleTests/Editor/Text/EditorTextViewTests.swift, KanvasExample/Podfile.lock
Related WP PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16011
- Bugs with the frame reordering logic (Fixes #96, Fixes #100)
- Adjusts scrolling logic so that the scroll position doesn't jump around as much
- Masks a crash coming from inside of UIFeedbackGenerator (Fixes #98)
- Adds a setting (`features.resizesFont`) to disable or enable dynamic font resizing (Fixes #70)
- Updates current selection when Multi Editor appears (Fixes #63)
=> Stories: 16.8 Bug Fixes

Classes/Editor/EditorView.swift, Classes/Editor/MultiEditor/MultiEditorViewController.swift, Kanvas.podspec
WordPress PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16109
This was an alignment issue with text when using OpenGL + `scaleToFill` content mode.
<details>
<summary><strong>Demo</strong></summary>
Notice the disappearing text after the confirm button is pressed.
<table>
<tr>
<th>Before</th>
<th>After</th> 
</tr>
<tr>
<td><video src="https://user-images.githubusercontent.com/3250/111414450-a6237700-86a5-11eb-8ef7-dfc69614651a.mp4"/></td>
<td><video src="https://user-images.githubusercontent.com/3250/111414415-96a42e00-86a5-11eb-8422-9216ad73857a.mp4"/></td>
</tr>
</table>
</details>
We now check the player's content mode before adjusting the size of the drawing & movable canvas views. These views are already properly sized to match the full size of the editor so we don't …
=> Stories: Scale to fill rendering + post-export overlays bug fixes

Classes/Editor/EditorView.swift, Classes/Editor/EditorViewController.swift, Classes/Editor/Text/EditorTextController.swift, Classes/Settings/CameraSettings.swift, Kanvas.podspec, KanvasExample/KanvasExampleTests/Editor/EditorViewTests.swift, KanvasExample/Podfile.lock
WordPress PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16229
- Adds a new `CameraSettings.aspectRatio` value
- Constrains player and editor views to the `CameraSettings.aspectRatio` value.
<a href="https://user-images.githubusercontent.com/3250/114083673-86c6d680-986c-11eb-9808-e2a2ec48ac27.PNG"><img src="https://user-images.githubusercontent.com/3250/114083673-86c6d680-986c-11eb-9808-e2a2ec48ac27.PNG" width="300"></a>
=> Add Aspect Ratio setting to resize + crop media

Classes/Recording/VideoOutputHandler.swift
While recording a video and dismissing the app through multitasking, the app will crash with a `SIGKILL` error. The crash line indicates a stall with a `semaphore.wait()` call when stopping the recording:
https://github.com/tumblr/kanvas-ios/blob/bc3dff580897d0170fce3818b5179a44263125e5/Classes/Recording/VideoOutputHandler.swift#L94
The reason seems to indicate a timeout issue with watchdog causing the crash:
```
Termination Description: SPRINGBOARD, <RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<org.wordpress>:10245 exhausted real (wall clock) time allowance of 10.00 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | …
```
=> Fixes a crash when recording & multitasking

Classes/MediaFormats/GIFEncoder.swift, Classes/Rendering/MediaExporter.swift, KanvasExample/Gemfile.lock
This PR updates the exporting loops for creating GIF to be wrapped with autorelease blocks so the memory pressure is smaller when exporting then.
Related bug: https://jira.tumblr.net/browse/PROD-15147
How to test: 
- Start the sample project
- Try to export a larger GIF ( you can get a GIF here: https://zikkimyeyin.tumblr.com/post/651438616631033856 )
- Check that the memory being used does not go over the limits.
=> Improve memory pressure while exporting GIFs

Classes/MediaFormats/GIFEncoder.swift, Classes/Rendering/MediaExporter.swift, Gemfile.lock, KanvasCamera.podspec, KanvasCameraExample/Gemfile.lock, KanvasCameraExample/Podfile.lock, KanvasCameraExample/Pods/Local Podspecs/KanvasCamera.podspec.json, KanvasCameraExample/Pods/Manifest.lock, KanvasCameraExample/Pods/Target Support Files/KanvasCamera/ResourceBundle-KanvasCamera-KanvasCamera-Info.plist, KanvasExample/KanvasExample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
This PR updates the exporting loops for creating GIF to be wrapped with autorelease blocks so the memory pressure is smaller when exporting then.
Related bug: https://jira.tumblr.net/browse/PROD-15147
How to test: 
- Start the sample project
- Ensure metal options are active.
- Try to export a larger GIF ( you can get a GIF here: https://zikkimyeyin.tumblr.com/post/651438616631033856 )
- Check that the memory being used does not go over the limits.
=> Version 1.0.4 with fix for export gifs

Resources/MetalShaders/shaders.metal
Fixes #120
See: https://jira.tumblr.net/browse/PROD-15637
This PR changes the variable types on the kernelIdentity shader in order for this check to work properly:
`(inWidth - outWidth) > 0`
Using `uint` will make this comparation to always be true even when outWidth is larger than inWidth.
It will also cause the offsset to overflow and be a large number and cause the bug we observe.
Up until now we have been *lucky* that the outTexture was always smaller, and that is also why the bug only manifested itself on certain hardware depending of the screen sizes and video resolution calculations.
- Start the demo app on a real device. On my tests I need to use an iPhone 12 Pro to see the original bug.
-  Disable Camera Open GL and Camera Open GL Capture
-  Enable Camera Metal and Metal Filters …
=> Fix kernel identify shader on Metal.

Classes/Camera/CameraController.swift, Classes/Editor/EditorView.swift, Classes/Editor/EditorViewController.swift, KanvasExample/KanvasExampleTests/Editor/EditorControllerTests.swift, KanvasExample/KanvasExampleTests/Editor/EditorViewTests.swift, KanvasExample/KanvasExampleTests/Editor/MultiEditor/MultiEditorControllerTests.swift
In https://github.com/tumblr/kanvas-ios/pull/122 we tried to move calls to `EditorView.setupViews` until later in the view cycle in order to ensure the `delegate` property was set so that methods like `getQuickPostButton` would be available at the appropriate time.
This caused some unintended side effects for view set up and produced a blank screen for the editor.
Instead, we'll revert to an older iteration where the delegate is passed it at initialization time to ensure it exists before the existing `setupViews` call is made.
=> Move EditorView delegate to initializer

Classes/Editor/EditorViewController.swift
This sets the filter type used when exporting video. I think there was a bad merge somewhere and this got dropped from the file.
- Select a video from the photo library
- Apply a filter to that video
- Ensure that the filter is applied
=> Add filter type change from Tumblr app

Classes/Editor/MultiEditor/MultiEditorViewController.swift, Classes/Rendering/Renderer.swift, Kanvas.podspec
Memory consumption grows constantly when exporting multiple images due to calls to [`output`](https://github.com/tumblr/kanvas-ios/blob/4d715e09cae64acf149befcdff68e55e85af52b1/Classes/Rendering/Renderer.swift#L165) in the renderer. In instances where there's no delegate to process the renderer's pixel buffer, we can avoid running the function altogether.
This will help alleviate WPiOS out-of-memory crashes:
- [Related WPiOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/18550)
=> Reduce renderer memory consumption when exporting

Classes/Editor/Drawing/DrawingView.swift
When the color picker tool is used, [`DrawingController::showCanvas` gets called](https://github.com/tumblr/kanvas-ios/blob/main/Classes/Editor/EditorViewController.swift#L1196), which sets `DrawingView::temporalImageView`'s alpha to be 1. But as far as I can see, `temporalImageView` is not supposed to be visible as it works as just a buffer to hold a drawing stroke. 
1. Run KanvasExample
2. Start
3. Select a picture to go to the editor screen
4. Select the drawing tool 
5. Select the color picker and pick color from the picture
6. Try to draw a line
Make sure the line drawn in the step 6 is not duplicated.
=> temporalImageView is not supposed to be visible

Example/KanvasExample/SplitViewController.swift
When running the sample app, there is a crash when swiping on the `MockDashboardViewController`. 
1. `pod install` on the sample app and open the .xcworkspace
2. run on a simulator
3. grant access to camera and microphone when prompted
4. close kanvas
5. use the text button that says "Open Kanvas Dashboard" 
6. swipe left on kanvas
7. swipe left on kanvas
8. (should not crash after second swipe left)
=> [ICORE-5154] Fix crash when accessing viewControllers in array

Classes/Editor/MultiEditor/MultiEditorViewController.swift, Example/Podfile.lock, Kanvas.podspec
Deleting one image causes the next one not to load in the editor.
Issue found in https://github.com/wordpress-mobile/WordPress-iOS/issues/16966 but can also be reproducible on the example app
I found the issue to be related to layout updates.
When `mediaClipWasDeleted` in `MultiEditorViewController` is called, we set the new selection `selected = newSelection` which in turns call `loadEditor` method. 
Normally, after `load(childVIewController:into)` is called the selected image is loaded. However, when the previous image is deleted, the editor does not layout automatically and the image does not appear.
`load(childVIewController:into)` itself is implemented [using recommended patterns](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaCon …
=> Multiple exports: Deleting one image causes the next one not to load in the editor

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Adds `CHANGELOG.md`. Based on https://github.com/wordpress-mobile/WordPressKit-iOS/pull/545 and the PR template iteration from https://github.com/wordpress-mobile/WordPressUI-iOS/pull/119.
=> Add `CHANGELOG.md`

CHANGELOG.md, Example/Podfile.lock, Kanvas.podspec
This PR updates the podspec version of kanvas and the changelog.
---
=> Bump up version to 1.4.6

CHANGELOG.md, Classes/Editor/EditorViewController.swift, Example/Podfile.lock, Kanvas.podspec
This PR sets aspectRatioLockDimensionSwapEnabled to `true` on the crop controller which makes the crop box swap its dimensions depending on portrait/landscape images. This fixes a recently reported issue where cropped image shifts during rotating 180 degrees.
- cd kanvas-ios/Example
- bundle exec pod install
- Run the example app
- If you are on the Sim make sure to enable metal related switches
- Select an image
- Tap on the crop & rotate icon
- Tap on the crop presets and select the square preset 
- Rotate the image 180 degrees
- Observe that the cropped area doesn't change
=> Make the crop box swap its dimensions depending on portrait/landscape images

Classes/Camera/CameraController.swift, Classes/Camera/MediaArchiver.swift, Classes/MediaFormats/GIFEncoder.swift, Classes/Rendering/MediaExporter.swift
- `DispatchQueue.global` usage could lead to thread explosion. This PR is to replace it by using Swift concurrency.
- Upgrade Xcode version to 14.3
- Enable the `Multiple Exports`
- Add multiple images
- Confirm then tap Post button
- **Expected**: The app should work normally.
=> Replace DispatchQueue.global by Swift concurrency

Classes/Camera/CameraInputController.swift
- Image becomes stretched after taking a shot in GIF mode.
In `scaleMediaToFill = true` mode, this [logic](https://github.com/tumblr/kanvas-ios/blob/1496390be9feceb73ee8c056a722df0a0e4db116/Classes/Rendering/Renderer.swift#L224) will be applied for the **width**.
```
inputDimensions.height * (scaleToFillSize.width / scaleToFillSize.height)
```
But in the current code, the same logic still applies [here](https://github.com/tumblr/kanvas-ios/blob/1496390be9feceb73ee8c056a722df0a0e4db116/Classes/Camera/CameraInputController.swift#LL554C7-L554C7) when calculating `recordingDimensions`
```
// Make recording resolution have the same aspect ratio as the screen
dimensions.width = dimensions.height * (frameSize.width / frameSize.height)
```
So this should cause the mismatched logic, then making …
=> Fix streched GIF image issue

Classes/Preview/CameraPreviewViewController.swift, Example/KanvasExampleTests/CameraPreview/CameraPreviewControllerTests.swift
GIFs sometimes aren't encoded when the CameraMode is set to gif. This is as there's a `settings.feature.gifs` flag we check that determines if gifs should be enabled.
It's possible to use the API to trigger a CameraViewController on gif mode without having this feature on. This is [a bug](https://github.com/tumblr/kanvas-ios/issues/160) in itself but for the time being this PR ensures that if a user has selected the gif camera and taken a photo we always encode that gif. Prior to now the gif was coming out as a video.
I've made this function testable and added a test. The commit with the actual functionality change is below:
[The fix commit](https://github.com/tumblr/kanvas-ios/pull/159/commits/a66a7e4179d588fcd6deef88f3dcf3461eefa158)
Use a real device for both tests
* Load the example …
=> Encode gif if CameraMode is set to GIF

CHANGELOG.md, Example/Podfile.lock, Kanvas.podspec
Updates Kanvas version, example project and change log to 1.4.9
---
=> Upgrade Kanvas to 1.4.9

Classes/Editor/EditorViewController.swift, Classes/Editor/Menu/EditionMenu/EditionMenuCollectionController.swift
A crash occurs on iOS when trying to call on `dequeueReusableCell` method when it isn't used for display.
This PR changes the method used to `cellForItem(at:)` instead to prevent crash. (Apple logs specifically mentions the improper use of `dequeue`)
While we are at it, the returned `cell` was passed to a non optional parameter, but all future uses of it was optional.
Turn the parameter to optional, and remove the `assertFailure` to make the application more resistant to crashes.
=> Fix iOS 18 cell dequeue crash

CHANGELOG.md, Classes/Camera/CameraController.swift, Classes/Camera/CameraPermissionsViewController.swift, Classes/Constants/KanvasStrings.swift, Classes/Editor/EditorView.swift, Classes/Editor/EditorViewController.swift, Classes/Editor/GIFMaker/Playback/PlaybackOption.swift, Classes/Editor/Media/TabBar/DrawerTabBarOption.swift, Classes/Editor/Menu/Shared/EditionOption.swift, Classes/Editor/Menu/StyleMenu/StyleMenuView.swift, Classes/Editor/Shared/ColorSelector/ColorSelectorView.swift, Classes/MediaPicker/MediaPickerViewController.swift, Classes/ModeSelector/ModeSelectorAndShootView.swift, Classes/Preview/CameraPreviewViewController.swift, Example/Podfile.lock, Kanvas.podspec
Updates `NSLocalizedStrings` to explicitly define a `value`.
This will make kanvas compatible with genstrings tool.
genstrings uses the value defined in the localized string to generate the key-value pair in the Localizable.strings file.
key - key
value - value
comment - comment for translators
Example:
```
NSLocalizedString("TryAgainKey", value: "Try again", comment: "Title for a button that allows the user to retry an action.")
/* Title for a button that allows the user to retry an action.*/
"TryAgainKey" = "Try again";
```
=> Localized strings update

.buildkite/pipeline.yml, .buildkite/validate_podspec_annotation.md
This will allow adopting an improved default pipeline upload step on the CI infrastructure side of the setup. It also makes it clear what queue is in use just by looking at the pipeline file.
Notice it does not introduce the standard `shared-pipeline-vars` file because to use that we first need the default pipeline upload step in the IaC configuration.
See https://linear.app/a8c/issue/AINFRA-283
=> AINFRA-283 - Set `queue: mac` explicitly in pipeline
